### PR TITLE
Tags improved

### PR DESCRIPTION
**Pull request by theboxer**
Added super box select for tags.

### CODE REVIEW

**Comment by jpdevries** [comment]
reset up my localhost, i think something is messed up with the connector, but i will look into that. i rebuilt a package and tested it on cloud and tags seem to work as expected. awesome work on this!
image

**Comment by jpdevries** [comment]
one thing i did notice is that if you open a resource that has tags, and say remove a tag, the save button doesn't re-enable. need trigger that whenever there is a change

**Comment by jpdevries** [comment]
i think MODx.fireResourceFormChange(); is what needs to be called but not sure where/how

**Comment by theboxer** [comment]
I will check that and create a pull request...

**Comment by jpdevries** [comment]
Thanks. Sorry I didn't catch that before merging this one
—

**Pull request merged**
