### PR TITLE
Refactor for MODX 3 (for a separate branch to the current 2.x)

### PR DESCRIPTION
**Pull request by muzzwood**
It's in a working state after the refactor. Still a work in progress though. Some of the update/notification services may not yet be working.

I also need to redo the build script and get a resolver together to update the resource class_key fields in the database.

### CODE REVIEW

**Comment by muzzwood** [comment]
The following PRs for core and Archivist need to be made for this to work properly too:

https://github.com/modxcms/revolution/pull/16079
https://github.com/modxcms/Archivist/pull/17

**Comment by JoshuaLuckers** [comment]
@muzzwood thanks for helping out! Do you want me to create a separate branch for these changes? 
We could also submit a request to MODX LLC to grant you maintainer access to this repo if that's more convenient.

**Comment by muzzwood** [comment]
Oh a separate branch would be fantastic, thanks! :)

**Comment by JoshuaLuckers** [comment]
@muzzwood done

**Comment by muzzwood** [comment]
I plan on testing it some more but so far it seems to be working nicely.
It could certainly use a bit of CSS polish to match the MODX 3 theme though.

Some pics:

Screenshot 2022-02-27 at 17-12-46 Editing Articles MODX Revolution


Screenshot from 2022-02-27 17-13-52


Screenshot from 2022-02-27 17-13-35

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/upgrademodx-working-to-upgrade-to-modx-3/5017/2

**Comment by JoshuaLuckers** [comment]
@muzzwood amazing work! I'll try my best to test it sometime in the upcoming days.

**Comment by JoshuaLuckers** [comment]
@muzzwood any idea why this is happening? 
Screen Shot 2022-03-01 at 13 27 47

**Comment by SnowCreative** [comment]
Is Quip MODX 3 compatible?

**Comment by muzzwood** [comment]
Huh. Not sure what's going on there - some form of escaping perhaps? I know Articles hard-codes a bunch of snippet calls into its templates. I'll look into that tomorrow.

**Comment by muzzwood** [comment]
This is an odd one... Any _uncached_ snippet tags added to the template won't be parsed.

**Comment by JoshuaLuckers** [comment]
@muzzwood The template refers to placeholders like `comments`. 

The values of these placeholders are set here:
https://github.com/modxcms/Articles/blob/266a6e74b312e924fb819d48a53cdca9abca574f/core/components/articles/src/Model/Article.php#L38-L40

I think the parser is doing something odd.

**Comment by muzzwood** [comment]
Yeah it's interfering somewhere with the parser but I haven't worked out where yet. 😅 

It affects any uncached snippet at all. You can create a new snippet, add it to a template that Articles is using, and you'll see it there unparsed.

**Comment by JoshuaLuckers** [comment]
> You can create a new snippet, add it to a template that Articles is using, and you'll see it there unparsed.

If you create a new resource (document) with template `sample.ArticleTemplate` the uncached snippet works fine. 


So my guess is that, since a regular resource parses it just fine and `Article` is an extension of this class, it has something to do with the `getContent` method in the `Article` class: https://github.com/modxcms/Articles/blob/266a6e74b312e924fb819d48a53cdca9abca574f/core/components/articles/src/Model/Article.php#L55

**Comment by muzzwood** [comment]
I've spent a couple of hours this afternoon trying to solve it but no luck.
I've disabled comments by default for now. (They can still be turned on in the Advanced Settings tab on the Articles container).

While comments are disabled, the issue doesn't show itself and all other snippets work properly.

I've tried the same Quip calls on a non-Articles resource/template and they work fine. So it's not Quip by itself that has the problem I think.

**Comment by JoshuaLuckers** [comment]
@muzzwood I found the solution, some of the placeholders in the templates should be uncached, e.g 
```
[[!+comments_enabled:is=`1`:then=`&nbsp;| <a href="[[~[[*id]]]]#comments" class="comments">Comments ([[!+comments_count]])</a>`]]
```

**Comment by muzzwood** [comment]
Well done @JoshuaLuckers! I can confirm that works - I just pushed the change.

I'm still not entirely sure _why_ that's happening though... 🤔. I would have thought the values would just end up cached rather than the tags themselves not being parsed. 

I think this is at a *good enough* stage for an alpha v3 release. Quip and Archivist probably still need some tweaks though.
Perhaps in the next release, we can rework the resource template to look a bit nicer with the MODX 3.x layout.

**Comment by JoshuaLuckers** [comment]
I really appreciate you helping out! I think we should add you as a sponsor of this update in the release notes!

**Comment by muzzwood** [comment]
Hey, my pleasure! Thanks for all you do too, Joshua. 😃 
It was Mark who nudged me to help out, so if it's ok with you, reckon we could put modmore as the sponsor?

**Comment by JoshuaLuckers** [comment]
Sounds good to me!

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx3-after-update-all-resources-in-web-vanished-suspected-issues-with-articles/5141/2

**Pull request merged**
