### PR TITLE
Update articletemplate default Author

### PR DESCRIPTION
**Pull request by Eein**
Internally we have cases where we publish content on behalf of the client. The current configuration unfortunately shows the created-by name in the container, but then shows the editors name in the actual article.

This has really bugged me - Why is the default set to show the persons name who 'published' the article and not the 'person who wrote it'? I imagine that most content writers would want credit for their work; not the editor. This pull request changes the post author to the same person as "created by" in the article, effectively giving the author the credit, not the editor.

### CODE REVIEW

**Comment by jpdevries** [comment]
We should talk more about this. I'm not sure if the person who created an Article is anymore likely to be who "wrote it" then who published it. If I run a php script to create 1,000 articles it doesn't mean I wrote them. Seems like it should credit whatever user is set as the creator in the article edit panel. —

**Comment by theboxer** [comment]
@Eein by this change you remove credits to editors (I suppose they should have some credits also).

What do you thing about showing both names? Like Created by / Published by ?

That might give credits for the work writers and also editors.

John

**Comment by Eein** [comment]
The answer might be both; But generally a writer is credited, the editor is tasked only with ensuring the quality of material published for the organization. Generally editors only get credit for editing in the 'credits' of a book or script.

In terms of user experience it might be confusing for users to set a created by and published by field. Might have to reach out and find someone who uses this for content heavy sites and see what is the preferred default. I know our clients wouldn't be very happy if we put our name on their content :P 

I'm trying to think up specific scenarios where an editor credit would even be necessary unless enabled as an option in the settings.

The answer to this issue would probably be by answering the following questions:

What is the very generic use case? (as a base setup)
In more complicated enterprise cases, do they give editor credits?

You might see this type of thing used in content re-publishing, but re-publishers are often up to no good :P

**Comment by PeterKnightDigital** [comment]
I had this issue too when I was creating blog posts for clients. My solution is possibly too simple but I ended up creating a drop down list TV populated with author names. 
That way, I could just manually pick the author when I created the post. It wasn't very dynamic but it worked perfectly.

**Comment by jpdevries** [comment]
To me, this boils down to two simple questions:
- does this problem exist with modResource?
- should the Articles publish pane verge from the modResource pane?

I think the answers are No and No. Maybe there is a way to address this as a patch or minor bump, but I think this ultimately comes back to the problem that the publishing UX for modArticle deviates to greatly from modResource. 

A modResource has all these Settings:


Articles 1.x mad the assumption none of them are application to Articles.

**Comment by jpdevries** [comment]
I'm not sure we can make the case that `[[*createdby]]` is less likely to be accurate then `[[*publishedby]]`. I think the answer here is to expose all those fields to be editable.

**Comment by Mark-H** [comment]
In the case of Articles there is a createdby dropdown where you can select who should be created as the author, I'd say using the [[*createdby]] makes sense because of that.

**Comment by theboxer** [comment]
agree with mark

**Comment by boostventilator** [comment]
Also, the use of “published by” and “created by” is inconsistent and can cause confusion in the default Article Template and Article Row:

**Template: sample.ArticleTemplate**

`<span class="left">Posted on [[*publishedon:strtotime:date=`%b %d, %Y`]] by <a href="[[~[[*parent]]]]author/[[*publishedby:userinfo=`username`]]">[[*publishedby:userinfo=`username`]]</a></span>`

**Chunk: sample.ArticleRowTpl**
`<p class="post-info">[[%articles.posted_by]] <a href="[[~[[*id]]]]author/[[+createdby:userinfo=`username`]]">[[+createdby:userinfo=`username`]]</a>`

**Pull request closed without merging**
